#!/bin/bash
#
# TrueBit Incident Monitor (Simple Version)
# Monitors addresses every 5 minutes
# Two-stage process: analyze first, update only if significant
#

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATE_DIR="$PROJECT_DIR/.incident-monitor"
ETH_RPC="https://eth.llamarpc.com"
CHECK_INTERVAL=300  # 5 minutes

# Addresses to watch
ADDRESSES=(
  "0x6C8EC8f14bE7C01672d31CFa5f2CEfeAB2562b50"  # Attacker EOA
  "0x62AfDD1BD84F6b152572404BE90679Ae58Eb4862"  # Destination A (drained)
  "0x273589ca3713e7becf42069f9fb3f0c164ce850a"  # Destination B
  "0x6aEcB6ee5D7fa4f5b7B5553ED0173442F0EE5ccB"  # Intermediary
  "0xa567c6a2ac472936ed92DfE6A84CE211e42047f9"  # Message sender
  "0xD12f6E0fa7FBF4e3A1c7996E3F0Dd26AB9031a60"  # New Holding Address (from Dest A)
)

mkdir -p "$STATE_DIR"

get_state() {
  local addr=$1
  local method=$2
  curl -s -X POST "$ETH_RPC" \
    -H "Content-Type: application/json" \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"$method\",\"params\":[\"$addr\",\"latest\"]}" \
    | grep -o '"result":"[^"]*"' | cut -d'"' -f4
}

check_address() {
  local addr=$1
  local safe_addr=$(echo "$addr" | tr '[:upper:]' '[:lower:]')
  local state_file="$STATE_DIR/$safe_addr"

  local tx_count=$(get_state "$addr" "eth_getTransactionCount")
  local balance=$(get_state "$addr" "eth_getBalance")
  local current="${tx_count}:${balance}"
  local previous=$(cat "$state_file" 2>/dev/null || echo "")

  echo "$current" > "$state_file"

  if [[ -n "$previous" && "$current" != "$previous" ]]; then
    echo "CHANGED"
  else
    echo "OK"
  fi
}

# STAGE 1: Analyze if changes are significant
analyze_changes() {
  local changed_addrs=$1
  echo "$(date '+%H:%M:%S') 🔍 STAGE 1: Analyzing if changes are significant..."

  cd "$PROJECT_DIR"

  local output_file="$STATE_DIR/analysis_output.txt"

  claude --dangerously-skip-permissions "You are an analysis agent for the TrueBit hack monitoring system.

Changes detected on these addresses: $changed_addrs

YOUR TASK:
1. Use WebFetch to check Etherscan for the latest transactions on these addresses
2. Determine if there are SIGNIFICANT changes worth documenting:
   - Fund movements > 0.1 ETH
   - New on-chain messages
   - Transfers to new addresses
   - Any laundering activity (Tornado Cash, bridges, etc.)

VERY IMPORTANT: Your FINAL OUTPUT must be EXACTLY one of these two lines (nothing else):
SIGNIFICANT: <brief description of what changed>
NOT_SIGNIFICANT: <brief reason>

Write your result to a file at $output_file using the Write tool.
Do NOT output anything else after writing the file." 2>&1 | tee "$STATE_DIR/analysis.log"

  # Read result from file
  local result=""
  if [[ -f "$output_file" ]]; then
    result=$(cat "$output_file")
    rm -f "$output_file"
  fi

  # Fallback: try to parse from log if file not created
  if [[ -z "$result" ]]; then
    result=$(grep -E "^(SIGNIFICANT|NOT_SIGNIFICANT):" "$STATE_DIR/analysis.log" 2>/dev/null | head -1)
  fi

  echo "$result"
}

# STAGE 2: Research and update page
update_page() {
  local description=$1
  echo "$(date '+%H:%M:%S') 📝 STAGE 2: Researching and updating page..."

  cd "$PROJECT_DIR"

  claude --dangerously-skip-permissions "You are an autonomous research agent for the TrueBit hack investigation.

A significant change was detected: $description

=== YOUR TASKS ===
1. Research the change in detail using Etherscan (WebFetch)
2. Find transaction hashes, amounts, destinations, any messages
3. Update the SecurityIncident.vue page with a new entry

=== STRICT RULES ===

1. ONLY modify these files:
   - monitor/frontend/src/views/SecurityIncident.vue
   - monitor/frontend/package.json (version bump only)

2. DO NOT modify any other files.

3. NEVER remove or modify existing content. Only ADD new entries.

4. When adding a new update entry:
   - Read the file first to find the highest existing ID
   - Use the next sequential ID
   - Add to the BEGINNING of the updates array
   - Include Etherscan links for transactions
   - End content with:
     '<p class=\"text-xs text-slate-500 mt-2 italic\">This update was generated automatically by the tru.watch monitoring system running every 5 minutes.</p>'

5. Update timeline if significant (add at BEGINNING, renumber IDs from 1)

6. Update timestamps: lastResearchTime, pageLastUpdated

7. Version bump (SUB-PATCH versioning):
   - Only bump monitor/frontend/package.json version
   - If version is 'X.Y.Z', change to 'X.Y.Z.1'
   - If version is 'X.Y.Z.N', increment to 'X.Y.Z.(N+1)'
   - Example: 0.1.17 -> 0.1.17.1 -> 0.1.17.2

8. Commit format:
   feat(auto): <brief description>

   Generated by tru.watch autonomous monitoring

   Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>

9. Push to origin main after commit.

Proceed with the research and update."
}

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   TrueBit Incident Monitor v2.1 (Simple)                   ║"
echo "║   Watching ${#ADDRESSES[@]} addresses every 5 minutes                  ║"
echo "║                                                            ║"
echo "║   Two-stage process:                                       ║"
echo "║     1. Analyze if changes are significant                  ║"
echo "║     2. Update page only if warranted                       ║"
echo "║                                                            ║"
echo "║   Press Ctrl+C to stop                                     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Initial capture
echo "Capturing initial state..."
for addr in "${ADDRESSES[@]}"; do
  check_address "$addr" > /dev/null
done
echo "Ready. Monitoring every 5 minutes..."
echo ""

while true; do
  changes=""

  for addr in "${ADDRESSES[@]}"; do
    result=$(check_address "$addr")
    if [[ "$result" == "CHANGED" ]]; then
      echo "$(date '+%H:%M:%S') 🚨 Change detected: ${addr:0:10}..."
      changes="$changes $addr"
    fi
  done

  if [[ -n "$changes" ]]; then
    # STAGE 1: Analyze
    analysis=$(analyze_changes "$changes")
    echo "$(date '+%H:%M:%S') Analysis: $analysis"

    if [[ "$analysis" == SIGNIFICANT:* ]]; then
      description="${analysis#SIGNIFICANT: }"
      echo "$(date '+%H:%M:%S') ✓ Change is SIGNIFICANT"
      # STAGE 2: Update
      update_page "$description"
    else
      echo "$(date '+%H:%M:%S') ○ Not significant, skipping update"
    fi
  else
    echo "$(date '+%H:%M:%S') ✓ No changes"
  fi

  echo "$(date '+%H:%M:%S') Next check in 5 minutes..."
  echo ""
  sleep "$CHECK_INTERVAL"
done
