#!/bin/bash
#
# TrueBit Incident Monitor (Simple Version)
# Monitors addresses and spawns Claude Code when changes detected
#

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="$PROJECT_DIR/.incident-monitor"
ETH_RPC="https://eth.llamarpc.com"

# Addresses to watch
ADDRESSES=(
  "0x6C8EC8f14bE7C01672d31CFa5f2CEfeAB2562b50"  # Attacker EOA
  "0x62AfDD1BD84F6b152572404BE90679Ae58Eb4862"  # Destination A
  "0x273589ca3713e7becf42069f9fb3f0c164ce850a"  # Destination B
  "0x6aEcB6ee5D7fa4f5b7B5553ED0173442F0EE5ccB"  # Intermediary
  "0xa567c6a2ac472936ed92DfE6A84CE211e42047f9"  # Message sender
)

mkdir -p "$STATE_DIR"

get_state() {
  local addr=$1
  local method=$2
  curl -s -X POST "$ETH_RPC" \
    -H "Content-Type: application/json" \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"$method\",\"params\":[\"$addr\",\"latest\"]}" \
    | grep -o '"result":"[^"]*"' | cut -d'"' -f4
}

check_address() {
  local addr=$1
  local safe_addr=$(echo "$addr" | tr '[:upper:]' '[:lower:]')
  local state_file="$STATE_DIR/$safe_addr"

  local tx_count=$(get_state "$addr" "eth_getTransactionCount")
  local balance=$(get_state "$addr" "eth_getBalance")
  local current="${tx_count}:${balance}"
  local previous=$(cat "$state_file" 2>/dev/null || echo "")

  echo "$current" > "$state_file"

  if [[ -n "$previous" && "$current" != "$previous" ]]; then
    echo "CHANGED"
  else
    echo "OK"
  fi
}

spawn_claude_analysis() {
  local changed_addrs=$1
  echo "$(date '+%H:%M:%S') 🤖 Spawning Claude Code for analysis..."

  cd "$PROJECT_DIR"

  # Use a heredoc to pass the full prompt with rules
  claude --dangerously-skip-permissions "You are an autonomous monitoring agent for the TrueBit hack investigation.

Changes detected on addresses: $changed_addrs

=== YOUR TASKS ===
1. Check Etherscan for the latest transactions on these addresses
2. Analyze what happened (fund movement, messages, etc.)
3. If significant, update SecurityIncident.vue

=== STRICT RULES - YOU MUST FOLLOW THESE ===

1. ONLY modify these files:
   - monitor/frontend/src/views/SecurityIncident.vue
   - monitor/frontend/package.json (version bump only)

2. DO NOT modify any other files in the project.

3. NEVER remove or modify existing content in SecurityIncident.vue. Only ADD new entries.

4. When adding a new update entry:
   - Find the highest existing ID in the updates array
   - Use the next sequential ID (e.g., if highest is 9, use 10)
   - Add to the BEGINNING of the updates array (newest first display)
   - Include this note in the update content:
     '<p class=\"text-xs text-slate-500 mt-2 italic\">This update was generated automatically by the tru.watch monitoring system.</p>'

5. Update the timeline array if adding significant events:
   - Add new entries at the BEGINNING (newest first)
   - Renumber the timeline IDs sequentially from 1
   - Link to the correct updateId

6. Update these timestamps:
   - lastResearchTime
   - pageLastUpdated

7. Version bump:
   - Only bump monitor/frontend/package.json version
   - Increment patch version (e.g., 0.1.14 -> 0.1.15)
   - Do NOT bump backend or aggregator versions

8. Commit message format:
   feat(auto): <brief description of finding>

   Generated by tru.watch autonomous monitoring

   Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>

9. Only make changes if there are SIGNIFICANT new findings:
   - Fund movements (ETH moved to new addresses)
   - New transactions from/to monitored addresses
   - On-chain messages
   - Balance changes > 0.1 ETH

10. If no significant findings, just report 'No significant changes' and do NOT modify any files.

=== END RULES ===

Proceed with the analysis."
}

echo "╔════════════════════════════════════════════╗"
echo "║   TrueBit Incident Monitor                 ║"
echo "║   Watching ${#ADDRESSES[@]} addresses                    ║"
echo "║   Press Ctrl+C to stop                     ║"
echo "╚════════════════════════════════════════════╝"
echo ""

# Initial capture
echo "Capturing initial state..."
for addr in "${ADDRESSES[@]}"; do
  check_address "$addr" > /dev/null
done
echo "Ready. Monitoring every 60 seconds..."
echo ""

while true; do
  changes=""

  for addr in "${ADDRESSES[@]}"; do
    result=$(check_address "$addr")
    if [[ "$result" == "CHANGED" ]]; then
      echo "$(date '+%H:%M:%S') 🚨 Change detected: ${addr:0:10}..."
      changes="$changes $addr"
    fi
  done

  if [[ -n "$changes" ]]; then
    spawn_claude_analysis "$changes"
  else
    echo "$(date '+%H:%M:%S') ✓ No changes"
  fi

  sleep 60
done
